### ISSUE TITLE
Textual: unknown kwarg "path"

### ISSUE THREAD

**Issue by hanryhu** [dannyboland/clidb#10]
`clidb s3://path/to/s3/bucket` fails with error:
```
...
  File "/home/hhu/.local/lib/python3.8/site-packages/textual/app.py", line 203, in run_app
    app = cls(screen=screen, driver_class=driver, **kwargs)
  File "/home/hhu/.local/lib/python3.8/site-packages/clidb/cli.py", line 74, in __init__
    super().__init__(title="clidb", **kwargs)
TypeError: __init__() got an unexpected keyword argument 'path'
```

To prevent passing in unknown kwargs to `textual` , I suggest adding the line

```python
del kwargs[config_option]
```
in this loop:
https://github.com/dannyboland/clidb/blob/d33c69548859538936232c1a3200e08c96604e2d/src/clidb/cli.py#L71-L73

This unbreaks `clidb s3://path/to/s3/bucket`.

**Comment by dannyboland** [comment]
Thanks! I've pinned the exact textual version as well.
